# Generated by Django 4.2.7 on 2023-11-25 20:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('tag', models.CharField(max_length=8)),
                ('side', models.IntegerField(choices=[(-1, 'Lewo'), (1, 'Prawo')])),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('comment', models.TextField(blank=True, max_length=256, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 25, 21, 32, 25, 117468))),
                ('changed_on', models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 25, 21, 32, 25, 117468))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_bills.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_bills.currency')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_bills.billtype')),
            ],
        ),
    ]
